Bootstrap:docker
From:ubuntu:latest

%labels
  CREATOR Matthew Fortier
  UPDATED by Jade Skye
  PURPOSE To provide containerization of CLASSIC functionality
  VERSION 2.0

%setup
  # Adjust to use your own paths
  cp -R /home/jskye99/ECCCmaterial/CLASSIC-developFLUXNETupdate/tools/singularityContainerRecipe/para_netcdf_hdf-4.6.3 $SINGULARITY_ROOTFS

%post
  # Initial setup
  apt update

  # Install other tools required by the CLASSIC ecosystem
  apt install vim make curl build-essential git libnetcdff-dev git zip unzip python3 m4 gfortran libnetcdff-dev netcdf-bin nano zlib1g mpich doxygen python3 python3-pip nco libopenmpi-dev libgeos-dev libgdal-dev pandoc poppler-utils texlive-latex-base tree -y -f -m
  # Install jupyter-nbconvert (requires specific input for tzdata)
  echo tzdata tzdata/Areas string America |debconf-set-selections
  echo tzdata tzdata/Zones/America string Los_Angeles |debconf-set-selections
  DEBIAN_FRONTEND=noninteractive apt install tzdata -y
  apt install jupyter-nbconvert -y 

  # To deal with the Red Hat fortran modules path in the CLASSIC make file.
  mkdir -p /usr/lib64/gfortran
  ln -s /usr/include /usr/lib64/gfortran/modules

  # Necessary python tools for the CLASSIC ecosystem - order is important as cython depends on numpy
  pip3 install numpy
  pip3 install cython
  pip3 install cartopy # remove libproj-dev install from STEP 5 because it gets the wrong version for cartopy, then install cartopy here before anything else can trigger the same issue
  pip3 install ipykernel
  pip3 install pyyaml xarray pandas seaborn matplotlib statistics sklearn netcdf4 holoviews

  # Install CDO (must be done manually)
  mkdir -p /packages
  curl -o /packages/cdo-1.9.6.tar.gz "https://code.mpimet.mpg.de/attachments/download/19299/cdo-1.9.6.tar.gz"
  cd /packages
  tar -xzvf cdo-1.9.6.tar.gz cdo-1.9.6/
  rm cdo-1.9.6.tar.gz
  cd cdo-1.9.6
  ./configure
  make && make install

  # Setup parallel netcdf libraries. See README for more info on this.
  cd /para_netcdf_hdf-4.6.3/setup
  pwd
  ./setup_netcdf.sh
  ### Intel Fortran Compiler stuff:
  #./compiler/l_fortran-compiler_p_2022.1.0.134.sh -a -s --eula accept #--install-dir /home/jskye99/ECCC2022ContractWork/container_ops/CLASSIC_singularity_container/para_netcdf_hdf-4.6.3/setup/compiler/ifort_package
  #. /opt/intel/oneapi/setvars.sh
  ###
  chmod 777 -R /para_netcdf_hdf-4.6.3
  cd /para_netcdf_hdf-4.6.3
  cp setup/configure_zlib_patch /para_netcdf_hdf-4.6.3/setup/src/zlib-1.2.12/configure
  ./dobuild.mpi
  echo 'export LD_LIBRARY_PATH=/para_netcdf_hdf-4.6.3/MPI/lib$LD_LIBRARY_PATH' >>$SINGULARITY_ENVIRONMENT


