#!/bin/bash
set -e

# Script to stitch together CLASSIC output files split by row/lat bands across nodes onto the full domain.

# Usage: classic_stitch_netcdf.sh <directory_name> <threads>

#        where: directory_name = name of a CLASSIC output directory (defaults to the current directory)
#               threads        = number of OpenMP threads to use (defaults to 4)

# This script operates on directories labelled "netcdf_files_NN" where NN=01,02, ... 
# (generated by a CLASSIC model run) which may be located under <directory_name> or in an alternate location
# for the run under: /space/hall[5,6]/sitestore/eccc/crd/ccr[p,n]/ccr[p,n]_tmp/$USER/classic
# 
# The stitched files will be in "<directory_name>/netcdf_files".

# Notes:

# Use of "cdo" to do the stitching is limited to variables with up to 4 dimensions and has some side effects:
#
# 1) The lon/lat variables are converted from doubles to floats. 
# 2) Some attributes are added/removed. 
# 3) The time dimension is converted to a record dimension.

# Use of "nco" is required for higher dimensioned variables, but requires re-ordering/manipulation of
# the dimensions.

# Modifications:
#
# Ed Chan, Nov 2023:
#   - For regular lat-lon grids, fix processing of init files that are not global (i.e. regional domains).
# Ed Chan, Jul 2022:
#   - Allow ncks to use a default chunking policy for restart files (by not specifying one).
# Ed Chan, Jun 2022:
#   - Enable operation on directories located in either the user specified directory, or 
#     in an alternate location under /space/hall[5,6]/sitestore/eccc/crd/ccr[p,n]/ccr[p,n]_tmp
#   - Fix issue with newer version of ncrcat which uses the cell_methods convention by default
#     but garbles the netCDF "coordinates" attribute.
#   - Use nco 5.0.7/cdo 2.0.5 installed via a conda environment (account scrd530).
#     This eliminates the need to alter LD_LIBRARY_PATH.
#   - Added fix for cdo's truncation of long_name attributes exceeding 256 characters.
# Ed Chan, May 2022.
#   - Remove EC_LD_PREPEND from LD_LIBRARY_PATH as it interferes with ssm packages of nco/cdo.
# Ed Chan, Apr 2022.
#   - Migrate to U2 platforms.
# Ed Chan, Feb 2022. 
#   - Added support for files named the same as the variable it contains (e.g. sftlf.nc).
# Ed Chan, Nov 2021.
#   - For projectedGrid, fix ncks warning regarding appending lats/lons of different precision.
# Ed Chan, Jun 2021.
#   - Fix for perpft and N-cycle variables.
# Ed Chan, Oct 2020.
#   - Added support for coordinate variables longitude/latitude instead of lon/lat.
# Ed Chan, Jun 2020.
#   - Conversion of namelist parameters to shell variables now done for the 1st 50 lines 
#     of the job options file (instead of 30).
# Ed Chan, Apr 2020.
#   - Added support for higher dimensioned variables not supported by "cdo".
#     These are now processed using "nco". The stitching of the restart is now done
#     entirely using "nco".
# Ed Chan, Nov 2019.
#   - Use default versions of nco/cdo on ppp3/ppp4.
# Ed Chan, Apr 2019.
#   - Added support for rotated pole coordinates.
# Ed Chan, Mar 2019.
#   - Permute dimensions of slopefrac, if necessary, in support of older versions of CLASSIC.
#     This may be removed once permuted versions of slopefrac are no longer used.
# Ed Chan, Feb 2019.
#   - Make check for projectedGrid more robust.

# Initial implementation: Ed Chan, Dec 2018.

# ===============================================================================================

# --------------------------------
# Set various paths and variables.
# --------------------------------

# Ensure paths are set for nco and cdo utilities (that work on all systems).
export PATH=/space/hall5/sitestore/eccc/crd/ccrp/users/scrd530/conda/envs/utils/bin:$PATH

# Location of output files. Default to the current directory.

if [ -n "$1" ]; then
  output_directory=$1
else
  output_directory=.
fi

# Set number of OpenMP threads to use for "cdo". Default to 4.

if [ -n "$2" ]; then
  OMP_NUM_THREADS=$2
else
  OMP_NUM_THREADS=4
fi

# -----------------------------------------------------------------------------------------------

# ----------------------------------
# Obtain file/directory information.
# ----------------------------------

# Prevent script from proceeding if netcdf_files directory already exists.

[ -d $output_directory/netcdf_files ] && exit

# Get the temporary directory used for the run, if it exists.
# Otherwise, the output directory is used.

output_directory=$(readlink -f $output_directory)
group_dir=${output_directory%%/users*}
group=${group_dir##*/}
run_tmp=$group_dir/${group}_tmp/$USER/classic/$(echo ${output_directory##*/$USER/} | sed 's|/|_|g')
[[ ! -d $run_tmp ]] && run_tmp=$output_directory

# Get names of all subdirectories containing netCDF files.

cd $run_tmp
dirs=( netcdf_files_[0-9]* )

# Stop if no input directories are detected.

[ "${dirs[*]}" = "netcdf_files_[0-9]*" ] && echo 'No netCDF directories detected' && exit 1

# If only one input directory exists, then it contains files for the full domain. 
# Simply rename the directory.

[ "${dirs[*]}" = "netcdf_files_01" ] && mv netcdf_files_01 $output_directory/netcdf_files && exit

# Set namelist parameters defined in the job options file as local shell variables. 
# Required parameters are typically defined within the first 50 lines, but this can be changed.

eval "$(head -50 netcdf_files_01/job_options* | sed -n -e 's/[&!]/#/g; s/,/;/g; s/ *= */=/gp')"
projectedGrid=$(echo $projectedGrid | tr '[:upper:]' '[:lower:]')

# Get the name of the restart file from the job options file.

rs_file_to_overwrite=${rs_file_to_overwrite##*/}

# -----------------------------------------------------------------------------------------------

# ---------------------------------------------------------------
# Merge files split into bands of rows/lats onto the full domain.
# ---------------------------------------------------------------

# Note: lons/lats are converted from doubles to floats by "cdo".

mkdir -p netcdf_files

# For rotated lat-lon grids, extract the rotated pole coordinates from the restart file.

mkdir tmp$$
if [ "$projectedGrid" = '.true.' ] ; then 
  ncks -h --no_abc -v rotated_pole ${dirs[0]}/$rs_file_to_overwrite tmp$$/rotpole.nc
  ncatted -h -O -a ,global,d,, tmp$$/rotpole.nc
fi

# Get the names of the files in each subdirectory. Filter out the restart file as it requires special processing.

files=$(cd ${dirs[0]} ; echo *.nc | sed "s/$rs_file_to_overwrite//")

# Construct a variable that, when expanded, will contain the paths to all files to be merged.

for dir in ${dirs[@]}
do
  input_files="$input_files $dir/\$file"
done

# Stitch all files except the restart. For rotated lat-lon grids, append the rotated pole 
# coordinates since the rotated_pole variable is skipped during stitching.

for file in $files
do
  vname=${file%_per*}
  vname=${vname%_*}
  vname=${vname%.nc}

  # Get number of dimensions (including time) and use cdo only if 4 or less. Otherwise, use nco.

  ndims=$(ncdump -h ${dirs[0]}/$file | fgrep "$vname(" | sed -e 's/^.*(\(.*\)).*/\1/' -e 's/,/ /g' | wc -w)

  if [ $ndims -le 4 ] ; then

    for dir in ${dirs[@]} ; do
      eval ncatted -h -O -a axis,longitude,o,c,X -a axis,latitude,o,c,Y -a coordinates,$vname,o,c,'"latitude longitude"' $dir/$file
    done

    eval cdo --history -s -P $OMP_NUM_THREADS collgrid,1 $input_files netcdf_files/$file

    # Work-around to fix cdo's truncation of long_name attributes exceeding 256 characters.
    longname=$(ncdump -h netcdf_files_01/$file | fgrep $vname | fgrep long_name | sed 's/^[^"]*"//; s/"[^"]*$//')
    if [[ $(echo $longname | wc -m) -gt 256 ]] ; then
      ncatted -h -O -a long_name,$vname,o,c,"$longname" netcdf_files/$file
    fi

  else

    # Loop over each partial file, making "lat" a record dimension.
    i=1
    cd netcdf_files
    for part in $input_files ; do
      eval ncpdq -h -a lat,time ../$part x0.nc
      ofile=$( echo 00$i.nc | tail -c7 )
      ncks -h --no-abc --mk_rec_dmn lat x0.nc $ofile
      rm x0.nc
      i=$((++i))
    done

    # Concatenate all partial files by lats/rows.
    ncrcat -h --no_cell_methods [0-9]*.nc x1.nc

    # Revert back to the original format but with unlimited time dimension, so chunking map "rd1" 
    # can be used (chunk size is set to the dimension size, except for the record dimension).
    ncks -h --no-abc --fix_rec_dmn lat x1.nc x2.nc
    ncpdq -h -a time,lat x2.nc x3.nc
    ncks -h --no-abc --mk_rec_dmn time --cnk_plc=g3d --cnk_map=rd1 x3.nc $file

    # Add attributes identifying coordinate variables
    ncatted -h -O -a axis,longitude,o,c,X -a axis,latitude,o,c,Y -a coordinates,$vname,o,c,"latitude longitude" $file

    rm x*.nc [0-9]*.nc
    cd ..
  fi

  # For rotated lat-lon grids, append the rotated pole coordinates.
  [ "$projectedGrid" = '.true.' ] && ncks -h --no_abc -A tmp$$/rotpole.nc netcdf_files/$file
done

# -----------------------------------------------------------------------------------------------

# ---------------------------------------------------------------
# Reconstitute the restart file from partially modified versions.
# ---------------------------------------------------------------

# The restart file requires special processing. Each subdirectory contains a copy of the restart 
# file for the full domain but only a band of rows/lats are overwritten in each file. 
# The modified bands must first be extracted and then stitched together.

cd tmp$$

# Set variables depending on the type of grid.

if [ "$projectedGrid" != '.true.' ] ; then
  # Get latitudes from one of the restart files.
  lats=( $(ncks --cdl -C -v lat ../${dirs[0]}/$rs_file_to_overwrite | fgrep 'lat =' | tail -1 | sed -e 's/[;,]//g; s/^ *lat = //') )
fi

# Extract the modified row/lat band of the restart file from each node into 
# separate files using information stored in the domain_partitions.txt file. 

for i in ${!dirs[@]}
do
  # Extract lat/row bounds.
  line=$(tail -n +$((i+2)) $output_directory/run_files/domain_partitions.txt | head -1)
  bnd1=$(echo $line | cut -d ' ' -f2)
  bnd2=$(echo $line | cut -d ' ' -f3)

  if [ "$projectedGrid" = '.true.' ] ; then
    # If bounds are rows, convert indexing from Fortran to nco.
    bnd1=$((bnd1 - 1))
    bnd2=$((bnd2 - 1))
  else
    # If bounds are latitudes, then convert them to row bounds.
    [ $i -eq 0 ] && bnd1=-90
    [ $((i+1)) -eq ${#dirs[@]} ] && bnd2=90
    rows=()
    for j in ${!lats[@]}
    do
      [ $(echo "$bnd1 < ${lats[$j]} && ${lats[$j]} < $bnd2" | bc) == 1 ] && rows+=($j)
    done
    bnd1=${rows[0]}
    bnd2=${rows[-1]}
  fi

  # Extract the modified sub-domain from each restart file.
  ncks -h --no-abc -d lat,$bnd1,$bnd2 ../${dirs[$i]}/$rs_file_to_overwrite sub1.nc

  # Make lat the first dimension. All variables have "tile" as the 1st dimension, except one (has "months" instead).
  ncpdq -h -a lat,tile sub1.nc sub2.nc
  ncpdq -h -a lat,months sub2.nc sub3.nc

  # Convert lat to a record dimension.
  ofile=$( echo 00$i.nc | tail -c7 )
  ncks -h --no-abc --mk_rec_dmn lat sub3.nc $ofile
  rm sub*
done

# Merge the extracted portions from each of the restart files and revert back to the original format.
# NB: Newer versions of ncrcat default to using the cell_methods convention which according to
#     nco docs, "may alter metadata in an undesirable (or possibly incorrect) fashion". 
#     Since it garbles the coordinates attribute, it is switched off.

ncrcat -h --no_cell_methods [0-9]*.nc x1.nc

ncks -h --no-abc --fix_rec_dmn lat x1.nc x2.nc
ncpdq -h -a tile,lat x2.nc x3.nc
ncpdq -h -a months,lat x3.nc rs.nc
rm x*nc [0-9]*.nc

# For rotated lat-lon grids, append the rotated pole coordinates.

[ "$projectedGrid" = '.true.' ] && ncks -h --no_abc -A rotpole.nc rs.nc

# Fix some attributes. 

ncatted -h -O -a standard_name,tile,d,, -a calendar,tile,d,, -a units,tile,d,,  -a axis,tile,d,, -a history,global,d,, \
        -a created_by,global,d,, -a row_bounds,global,d,, \
        -a creation_date,global,o,c,"$(date)" rs.nc ../netcdf_files/$rs_file_to_overwrite

cd ..
rm -rf tmp$$

# Move final stitched directory to user specified output directory.

if [[ $run_tmp != $output_directory ]] ; then 
  mv netcdf_files $output_directory
  #rm -f $output_directory/run_files/${run_tmp##*/}
fi

exit
